spring.application.name=security_study
spring.datasource.url=jdbc:mariadb://127.0.01:3307/steam`

spring.datasource.username=root`

spring.datasource.password=4658`

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update